import { Bebas_Neue, Raleway } from "next/font/google";
import "./globals.css";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400", // Bebas Neue only has one weight
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"], // Added common weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bebasNeue.variable} ${raleway.variable} h-full antialiased`}
    >
      {/* Set Raleway as the global default font for the body */}
      <body 
        className="min-h-full flex flex-col" 
        style={{ fontFamily: "'Raleway', sans-serif" }}
      >
        {children}
      </body>
    </html>
  );
}